//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationBundle
    {
        public int Id { get; set; }
        public long BundleID { get; set; }
        public string Information_Type { get; set; }
        public long InformationID { get; set; }
    }
}
