//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class konyv
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> writerID { get; set; }
        public Nullable<int> authorId { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> Categories { get; set; }
        public string Descrpition { get; set; }
        public Nullable<long> imageID { get; set; }
        public string demo { get; set; }
    }
}
