//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IdLog { get; set; }
        public int who { get; set; }
        public System.DateTime when { get; set; }
        public Nullable<int> what_ID { get; set; }
        public string whom { get; set; }
        public string what { get; set; }
    }
}
