//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader_Card
    {
        public int Id { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<long> Rent_ID_Bundle { get; set; }
        public string Personel_ID_Card { get; set; }
        public string home { get; set; }
        public string Momname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birtpalace { get; set; }
    }
}
