//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation_BookCategorie
    {
        public int Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<int> CatregorieID { get; set; }
    }
}
