//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int iduser { get; set; }
        public string Username { get; set; }
        public string role { get; set; }
        public Nullable<int> admin { get; set; }
        public string special_password { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
