//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Könyvtár
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writer
    {
        public int Id { get; set; }
        public string writer_name { get; set; }
        public string writer_Date { get; set; }
        public string aboutpath { get; set; }
    }
}
